"""adding updated at field

Revision ID: 9f1de33cfcdf
Revises: f300190abacb
Create Date: 2024-07-14 14:32:13.747655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1de33cfcdf'
down_revision: Union[str, None] = 'f300190abacb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index('email_updated_at_idx', 'users', ['email', 'updated_at'], unique=False)
    op.create_index('user_updated_at_idx', 'users', ['username', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_updated_at_idx', table_name='users')
    op.drop_index('email_updated_at_idx', table_name='users')
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
